# Generated by Django 2.1.5 on 2019-01-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0002_auto_20190128_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='restaurant_suggestions',
            new_name='title',
        ),
    ]
